using System;
using System.IO;
using System.Reflection;
using System.Collections.Generic;

namespace EasyTCP
{
	internal static class Program
	{
		internal static void Main(string[] args)
		{
			try
			{
				string InputPath, OutputPath;

				#region Adding Parameters
				OneStringParameter
					pNameSpace = new OneStringParameter("ns", "name", "namespace name (Default: no namespace)"),
					pOutputPath = new OneStringParameter("o", "path", "Output file (Default: Same name as file with '.cs' extension in the current folder)");

				var pUNP = new FlagParameter("unp", "Use null propagation");

				P.Add(pOutputPath);
				P.Add(pNameSpace);
				P.Add(pUNP);
				#endregion

				#region Arguments Analysis
				try
				{
					int
						ndx = 0,
						n = args.Length - 1;

					if (n < 0)
					{
						PrintUsage();
						return;
					}

					while (ndx < n)
					{
						string Option = args[ndx++];
						if (Option[0] != '-')
							throw new Exception("Parameters must be start with '-'");

						IParameter Param = null;
						string Code = Option.Substring(1);
						foreach (var X in P)
							if (X.Code == Code)
							{
								Param = X;
								break;
							}

						if (Param == null)
							throw new Exception("Unknown Parameter");

						Param.Process(args, ref ndx);
					}

					InputPath = args[ndx];
					OutputPath = pOutputPath.Value ?? Path.GetFileNameWithoutExtension(InputPath) + ".cs";
				}
				catch (Exception E)
				{
					PrintUsage("Error: " + E.Message);
					return;
				}
				#endregion

				var CG = new CodeGenerator(InputPath, pUNP.Exist);

				using (var SW = Global.SW = new IndentedStreamWriter(OutputPath))
				{
					SW.WriteLine("// auto-generated by EasyTCP (v{0})", Assembly.GetExecutingAssembly().GetName().Version.ToString(3));
					SW.WriteLine();

					SW.WriteLine("using System;");
					SW.WriteLine("using System.IO;");
					SW.WriteLine("using System.Text;");
					SW.WriteLine("using System.Threading;");
					SW.WriteLine("using System.Net.Sockets;");
					SW.WriteLine("using System.Collections.Generic;");

					SW.WriteLine();

					if (pNameSpace.Value == null)
						CG.Generate();
					else
					{
						SW.WriteLine("namespace {0}", pNameSpace.Value);
						SW.Block(CG.Generate);
					}
				}
			}
			catch (Exception E)
			{
				Console.WriteLine("----------------------------------------");
				Console.WriteLine("Error: " + E.Message);
				Console.WriteLine("Stack Trace: ");
				Console.WriteLine(E.StackTrace);
				Console.WriteLine("----------------------------------------");
			}
		}

		private static readonly List<IParameter> P = new List<IParameter>();

		private static void PrintUsage(string Message = null)
		{
			if (Message != null)
			{
				Console.WriteLine();
				Console.WriteLine(Message);
			}

			Console.WriteLine();
			Console.WriteLine("Usage: ");
			Console.WriteLine("   EasyTCP [Options] File");
			Console.WriteLine();
			Console.WriteLine("Options:");

			int MaxLen = 0;
			foreach (var X in P)
				MaxLen = Math.Max(MaxLen, (X.Code + X.CodeParams).Length);

			var Format = $"{{0,-{MaxLen + 1}}}";
			foreach (var X in P)
			{
				Console.Write("   -");
				Console.Write(Format, X.Code + " " + X.CodeParams);
				Console.WriteLine(" | " + X.Desc);
			}
		}
	}
}
